---
version: 1
disable_existing_loggers: false
loggers:
  '':
    level: DEBUG
    handlers: ["console_handler", "file_handler"]

handlers:
  console_handler:
    class: logging.StreamHandler
    formatter: console

formatters:
  default:
    format: "%(created)s %(threadName)s %(name)s:%(lineno)d - %(levelname)s: %(message)s"
