---
name: ci
on:
  push:
    paths-ignore:
      - "README.md"
      - "dev/**"
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  lint:
    name: flake8 lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install lint dependancies
        run: python3 -m pip install -r tests/requirements.txt
      - name: flake8
        run: flake8
